### ISSUE TITLE
为什么我配置了还是无法上传呢

### ISSUE THREAD

**Issue by kinpowoo** [wustor/PythoPackage#1]
按照您的教程写的

    task debugToFir {
        dependsOn 'assembleDebug'
        doLast {
            def upUrl = "http://api.fir.im/apps"
            def appName = "eestore"
            def bundleId = project.android.defaultConfig.applicationId
            def verName = project.android.defaultConfig.versionName
            def apiToken = "0a9dbfe3038a2d0c3e61690c1d183ab8"
            def iconPath = "D:/Android/Project/androidPad/EEStore/app/src/main/res/mipmap-xhdpi/app_icon.png"
            def apkPath = "D:/Android/Project/androidPad/EEStore/app/build/outputs/apk/eestorepad1.0.1.apk"
            def buildNumber = project.android.defaultConfig.versionCode
            def changeLog = "版本更新日志"
            //执行Python脚本
            def process = "python upToFir.py ${upUrl} ${appName} ${bundleId} ${verName} ${apiToken} ${iconPath} ${apkPath} ${buildNumber} ${changeLog}".execute()
            println("开始上传至fir")
            //获取Python脚本日志，便于出错调试
            ByteArrayOutputStream result = new ByteArrayOutputStream()
            def inputStream = process.getInputStream()
            byte[] buffer = new byte[1024]
            int length
            while ((length = inputStream.read(buffer)) != -1) {
                result.write(buffer, 0, length)
                println("开始上传至fir:"+length)
            }
            println(result.toString("UTF-8"))
            println "上传结束 "
        }
    }

**Comment by kinpowoo** [comment]
python是3.x版本，upToFir.py写放在了对的目录，感觉没起作用

**Comment by wustor** [comment]
用GitHub上面最新的代码，我看了下你不是最新的代码

**Comment by kinpowoo** [comment]
现在用了最新的了  在gradle.properties里加了APP_NAME 和 CHANGE_LOG， 还是上传不上去，感觉脚本没被执行
![qq 20180123133908](https://user-images.githubusercontent.com/19944251/35259838-03178682-0043-11e8-8610-050e06044f65.png)

**Comment by wustor** [comment]
你的token不对，我刚刚试了下你的token是无效的，你看看你的token值是不是跟fir官网上的不一样

**Comment by kinpowoo** [comment]
062cfbfa919907746f7eac5e4abc835c   这我重新生成的

**Comment by wustor** [comment]
1556473469，你加一下，我帮你看一下

**Comment by amazingCoderL** [comment]
我也遇到了这个问题，请问解决了吗 @wustor

**Comment by kinpowoo** [comment]
@amazingCoderL  你极有可能是 requests库没有装，用pip install requests 装一下，安装失败就科学上网装
