### ISSUE TITLE
python脚本报错

### ISSUE THREAD

**Issue by amazingCoderL** [wustor/PythoPackage#2]
Traceback (most recent call last):
  File "auto_package.py", line 52, in <module>
    upToFir()
  File "auto_package.py", line 6, in upToFir
    upUrl = sys.argv[1]
IndexError: list index out of range

**Comment by wustor** [comment]
你参数数量传的不不够，明显的数组越界，你可以先打印一下参数的数量

**Comment by amazingCoderL** [comment]
恩恩   应该执行gradle 的task去运行python脚本  我是直接运行的python脚本  所以报这个错了

**Comment by wustor** [comment]
好的，解决就好
